name: Build and deploy server

on:
  push:
    paths:
      - 'server/**'
      - ".github/workflows/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - 'server/**'
      - ".github/workflows/**"
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose